const affirmations = [
  "I am capable of learning difficult things.",
  "Progress matters more than perfection.",
  "I belong here, even when things feel hard.",
  "My effort today is building my future.",
  "I am allowed to take up space and succeed.",
  "I can handle challenges one step at a time.",
  "Every study session counts, even the short ones.",
  "I am becoming more confident through practice.",
  "I trust myself to figure things out.",
  "I am doing better than I think.",
  "My discipline today supports my goals tomorrow.",
  "It’s okay to ask for help when I need it.",
  "I am growing, even on slow days.",
  "I deserve rest without guilt.",
  "I can balance ambition and well-being.",
  "Small wins are still wins.",
  "I am capable of academic success.",
  "I don’t need to have everything figured out.",
  "Consistency beats motivation.",
  "I can recover from setbacks.",
  "I am learning how to manage my time better.",
  "My hard work will pay off.",
  "I can focus on what I can control.",
  "I am proud of myself for showing up.",
  "I am allowed to learn at my own pace.",
  "Mistakes help me improve.",
  "I am resilient under pressure.",
  "I can do hard things, even when tired.",
  "I am building habits that support my future.",
  "My goals are achievable.",
  "I am more prepared than I feel.",
  "I can improve with practice.",
  "My education is an investment in myself.",
  "I am capable of growth and change.",
  "I don’t need to compare myself to others.",
  "I can reset and refocus anytime.",
  "My effort matters.",
  "I trust the process I’m in.",
  "I am developing valuable skills.",
  "I can adapt when plans change.",
  "I am allowed to take breaks and still succeed.",
  "I am learning to manage stress effectively.",
  "I can prioritize what matters most today.",
  "I am proud of my persistence.",
  "I am capable of finishing what I start.",
  "I am worthy of academic confidence.",
  "I can handle deadlines responsibly.",
  "I am improving one day at a time.",
  "My focus creates results.",
  "I am doing my best with what I have.",
  "I am allowed to feel challenged and continue anyway.",
  "I am growing into a capable adult.",
  "I can learn from feedback without fear.",
  "My work ethic is getting stronger.",
  "I am allowed to be both ambitious and human.",
  "I am committed to my goals.",
  "I can overcome procrastination with small steps.",
  "I am developing self-discipline.",
  "I can trust myself to keep going.",
  "I am preparing myself for future opportunities.",
  "I am capable of meaningful progress.",
  "I can manage my responsibilities.",
  "I am becoming more confident academically.",
  "I can learn even when things feel confusing.",
  "I am allowed to take things one day at a time.",
  "I am building momentum.",
  "I am capable of meeting expectations.",
  "I am learning how to succeed on my own terms.",
  "I can focus my energy productively.",
  "I am resilient and adaptable.",
  "I can keep going, even when it’s uncomfortable.",
  "I am creating a strong foundation for my future.",
  "I am learning how to handle pressure.",
  "I can stay committed even on tough days.",
  "I am proud of my academic journey.",
  "I can improve my habits gradually.",
  "I am capable of balancing multiple priorities.",
  "I am becoming more self-reliant.",
  "I can trust my preparation.",
  "I am developing confidence through action.",
  "I am allowed to grow without rushing.",
  "I am capable of long-term success.",
  "I can stay consistent with my goals.",
  "I am doing meaningful work.",
  "I can succeed through persistence.",
  "I am learning how to believe in myself.",
  "I am capable of reaching my potential.",
  "I can keep improving every day.",
  "I am proud of how far I’ve come.",
  "I am becoming the person I want to be.",
  "I can face today with confidence."
];

// Get today's date as a number
const today = new Date();
const dayNumber = Math.floor(today.getTime() / (1000 * 60 * 60 * 24));

// Pick affirmation based on day
const affirmationIndex = dayNumber % affirmations.length;

document.getElementById("affirmation").textContent =
  affirmations[affirmationIndex];
